import { Injectable } from '@angular/core';
import { Currency } from '../models/currency';

@Injectable({
  providedIn: 'root'
})
export class CurrenciesService {
  getCurrency(code: string): Currency | undefined {
    return this.currencies.find(c => c.code === code);
  }

  currencies = [
    new Currency("AED", "UAE Dirham"),
    new Currency("AFN", "Afghani"),
    new Currency("ALL", "Lek"),
    new Currency("AMD", "Armenian Dram"),
    new Currency("ANG", "Netherlands Antillean Guilder"),
    new Currency("AOA", "Kwanza"),
    new Currency("ARS", "Argentine Peso"),
    new Currency("AUD", "Australian Dollar"),
    new Currency("AWG", "Aruban Florin"),
    new Currency("AZN", "Azerbaijan Manat"),
    new Currency("BAM", "Convertible Mark"),
    new Currency("BBD", "Barbados Dollar"),
    new Currency("BDT", "Taka"),
    new Currency("BGN", "Bulgarian Lev"),
    new Currency("BHD", "Bahraini Dinar"),
    new Currency("BIF", "Burundi Franc"),
    new Currency("BMD", "Bermudian Dollar"),
    new Currency("BND", "Brunei Dollar"),
    new Currency("BOB", "Boliviano"),
    new Currency("BOV", "Mvdol"),
    new Currency("BRL", "Brazilian Real"),
    new Currency("BSD", "Bahamian Dollar"),
    new Currency("BTC", "Bitcoin"),
    new Currency("BTN", "Ngultrum"),
    new Currency("BWP", "Pula"),
    new Currency("BYN", "Belarusian Ruble"),
    new Currency("BZD", "Belize Dollar"),
    new Currency("CAD", "Canadian Dollar"),
    new Currency("CDF", "Congolese Franc"),
    new Currency("CHE", "WIR Euro"),
    new Currency("CHF", "Swiss Franc"),
    new Currency("CHW", "WIR Franc"),
    new Currency("CLF", "Unidad de Fomento"),
    new Currency("CLP", "Chilean Peso"),
    new Currency("CNY", "Yuan Renminbi"),
    new Currency("COP", "Colombian Peso"),
    new Currency("COU", "Unidad de Valor Real"),
    new Currency("CRC", "Costa Rican Colon"),
    new Currency("CUC", "Peso Convertible"),
    new Currency("CUP", "Cuban Peso"),
    new Currency("CVE", "Cabo Verde Escudo"),
    new Currency("CZK", "Czech Koruna"),
    new Currency("DJF", "Djibouti Franc"),
    new Currency("DKK", "Danish Krone"),
    new Currency("DOP", "Dominican Peso"),
    new Currency("DOT", "Polkadot"),
    new Currency("DZD", "Algerian Dinar"),
    new Currency("EGP", "Egyptian Pound"),
    new Currency("ERN", "Nakfa"),
    new Currency("ETB", "Ethiopian Birr"),
    new Currency("ETH", "Ethereum"),
    new Currency("EUR", "Euro"),
    new Currency("FJD", "Fiji Dollar"),
    new Currency("FKP", "Falkland Islands Pound"),
    new Currency("GBP", "Pound Sterling"),
    new Currency("GEL", "Lari"),
    new Currency("GHS", "Ghana Cedi"),
    new Currency("GIP", "Gibraltar Pound"),
    new Currency("GMD", "Dalasi"),
    new Currency("GNF", "Guinean Franc"),
    new Currency("GTQ", "Quetzal"),
    new Currency("GYD", "Guyana Dollar"),
    new Currency("HKD", "Hong Kong Dollar"),
    new Currency("HNL", "Lempira"),
    new Currency("HTG", "Gourde"),
    new Currency("HUF", "Forint"),
    new Currency("IDR", "Rupiah"),
    new Currency("ILS", "New Israeli Sheqel"),
    new Currency("INR", "Indian Rupee"),
    new Currency("IQD", "Iraqi Dinar"),
    new Currency("IRR", "Iranian Rial"),
    new Currency("ISK", "Iceland Krona"),
    new Currency("JMD", "Jamaican Dollar"),
    new Currency("JOD", "Jordanian Dinar"),
    new Currency("JPY", "Yen"),
    new Currency("KES", "Kenyan Shilling"),
    new Currency("KGS", "Som"),
    new Currency("KHR", "Riel"),
    new Currency("KMF", "Comorian Franc"),
    new Currency("KPW", "North Korean Won"),
    new Currency("KRW", "Won"),
    new Currency("KWD", "Kuwaiti Dinar"),
    new Currency("KYD", "Cayman Islands Dollar"),
    new Currency("KZT", "Tenge"),
    new Currency("LAK", "Lao Kip"),
    new Currency("LBP", "Lebanese Pound"),
    new Currency("LKR", "Sri Lanka Rupee"),
    new Currency("LRD", "Liberian Dollar"),
    new Currency("LSL", "Loti"),
    new Currency("LYD", "Libyan Dinar"),
    new Currency("MAD", "Moroccan Dirham"),
    new Currency("MDL", "Moldovan Leu"),
    new Currency("MGA", "Malagasy Ariary"),
    new Currency("MKD", "Denar"),
    new Currency("MMK", "Kyat"),
    new Currency("MNT", "Tugrik"),
    new Currency("MOP", "Pataca"),
    new Currency("MRU", "Ouguiya"),
    new Currency("MUR", "Mauritius Rupee"),
    new Currency("MVR", "Rufiyaa"),
    new Currency("MWK", "Malawi Kwacha"),
    new Currency("MXN", "Mexican Peso"),
    new Currency("MXV", "Mexican Unidad de Inversion (UDI)"),
    new Currency("MYR", "Malaysian Ringgit"),
    new Currency("MZN", "Mozambique Metical"),
    new Currency("NAD", "Namibia Dollar"),
    new Currency("NGN", "Naira"),
    new Currency("NIO", "Cordoba Oro"),
    new Currency("NOK", "Norwegian Krone"),
    new Currency("NPR", "Nepalese Rupee"),
    new Currency("NZD", "New Zealand Dollar"),
    new Currency("OMR", "Rial Omani"),
    new Currency("PAB", "Balboa"),
    new Currency("PEN", "Sol"),
    new Currency("PGK", "Kina"),
    new Currency("PHP", "Philippine Peso"),
    new Currency("PKR", "Pakistan Rupee"),
    new Currency("PLN", "Zloty"),
    new Currency("PYG", "Guarani"),
    new Currency("QAR", "Qatari Rial"),
    new Currency("RON", "Romanian Leu"),
    new Currency("RSD", "Serbian Dinar"),
    new Currency("RUB", "Russian Ruble"),
    new Currency("RWF", "Rwanda Franc"),
    new Currency("SAR", "Saudi Riyal"),
    new Currency("SBD", "Solomon Islands Dollar"),
    new Currency("SCR", "Seychelles Rupee"),
    new Currency("SDG", "Sudanese Pound"),
    new Currency("SEK", "Swedish Krona"),
    new Currency("SGD", "Singapore Dollar"),
    new Currency("SHP", "Saint Helena Pound"),
    new Currency("SLE", "Leone"),
    new Currency("SLL", "Leone"),
    new Currency("SOS", "Somali Shilling"),
    new Currency("SRD", "Surinam Dollar"),
    new Currency("SSP", "South Sudanese Pound"),
    new Currency("STN", "Dobra"),
    new Currency("SVC", "El Salvador Colon"),
    new Currency("SYP", "Syrian Pound"),
    new Currency("SZL", "Lilangeni"),
    new Currency("THB", "Baht"),
    new Currency("TJS", "Somoni"),
    new Currency("TMT", "Turkmenistan New Manat"),
    new Currency("TND", "Tunisian Dinar"),
    new Currency("TOP", "Pa'anga"),
    new Currency("TRY", "Turkish Lira"),
    new Currency("TTD", "Trinidad and Tobago Dollar"),
    new Currency("TWD", "New Taiwan Dollar"),
    new Currency("TZS", "Tanzanian Shilling"),
    new Currency("UAH", "Hryvnia"),
    new Currency("UGX", "Uganda Shilling"),
    new Currency("USD", "US Dollar"),
    new Currency("USN", "US Dollar (Next day)"),
    new Currency("UYI", "Uruguay Peso en Unidades Indexadas (UI)"),
    new Currency("UYU", "Peso Uruguayo"),
    new Currency("UYW", "Unidad Previsional"),
    new Currency("UZS", "Uzbekistan Sum"),
    new Currency("VED", "Bolívar Soberano"),
    new Currency("VES", "Bolívar Soberano"),
    new Currency("VND", "Dong"),
    new Currency("VUV", "Vatu"),
    new Currency("WST", "Tala"),
    new Currency("XAF", "CFA Franc BEAC"),
    new Currency("XAG", "Silver"),
    new Currency("XAU", "Gold"),
    new Currency("XBA", "Bond Markets Unit European Composite Unit (EURCO)"),
    new Currency("XBB", "Bond Markets Unit European Monetary Unit (E.M.U.-6)"),
    new Currency("XBC", "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)"),
    new Currency("XBD", "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)"),
    new Currency("XCD", "East Caribbean Dollar"),
    new Currency("XDR", "SDR (Special Drawing Right)"),
    new Currency("XOF", "CFA Franc BCEAO"),
    new Currency("XPD", "Palladium"),
    new Currency("XPF", "CFP Franc"),
    new Currency("XPT", "Platinum"),
    new Currency("XSU", "Sucre"),
    new Currency("XTS", "Codes specifically reserved for testing purposes"),
    new Currency("XUA", "ADB Unit of Account"),
    new Currency("XXX", "The codes assigned for transactions where no currency is involved"),
    new Currency("YER", "Yemeni Rial"),
    new Currency("ZAR", "Rand"),
    new Currency("ZMW", "Zambian Kwacha"),
    new Currency("ZWL", "Zimbabwe Dollar")
  ];
}
